// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW4q69lgFuOOBCb8YnESGd6ogf9bzbhSw',
    appId: '1:495431379020:web:2bc5d6d49e8a76dacb6ce9',
    messagingSenderId: '495431379020',
    projectId: 'hotel-booking-3f7bf',
    authDomain: 'hotel-booking-3f7bf.firebaseapp.com',
    storageBucket: 'hotel-booking-3f7bf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_lzeR_TTyknKkOO5kXIU4SZchu9lhNuE',
    appId: '1:495431379020:android:65613eb5b3971a18cb6ce9',
    messagingSenderId: '495431379020',
    projectId: 'hotel-booking-3f7bf',
    storageBucket: 'hotel-booking-3f7bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO3P41w3xRFgUazf-99eRY8QuN0pK4ZE0',
    appId: '1:495431379020:ios:d96a18a43e2538a7cb6ce9',
    messagingSenderId: '495431379020',
    projectId: 'hotel-booking-3f7bf',
    storageBucket: 'hotel-booking-3f7bf.firebasestorage.app',
    iosBundleId: 'com.example.hotelBooking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAO3P41w3xRFgUazf-99eRY8QuN0pK4ZE0',
    appId: '1:495431379020:ios:d96a18a43e2538a7cb6ce9',
    messagingSenderId: '495431379020',
    projectId: 'hotel-booking-3f7bf',
    storageBucket: 'hotel-booking-3f7bf.firebasestorage.app',
    iosBundleId: 'com.example.hotelBooking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBW4q69lgFuOOBCb8YnESGd6ogf9bzbhSw',
    appId: '1:495431379020:web:966c57e3cea4c1d5cb6ce9',
    messagingSenderId: '495431379020',
    projectId: 'hotel-booking-3f7bf',
    authDomain: 'hotel-booking-3f7bf.firebaseapp.com',
    storageBucket: 'hotel-booking-3f7bf.firebasestorage.app',
  );
}
